######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 2 19:26:50 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myqt.h
FORMS += form.ui
SOURCES += main.cpp myqt.cpp
