######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 2 04:06:34 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello_qt.cpp
