######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 2 05:44:09 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += form.ui
SOURCES += main.cpp
